// Printable document helpers.
// Desktop/PWA browser: iframe.print().
// Android APK: print() is a no-op — deliver a printable HTML/PDF file via Share instead.

import { deliverBlob, deliverText, isAndroidNative } from "./file-delivery.js";

function buildDocHtml(title, bodyHtml){
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title>
<style>
  body{font-family:Segoe UI,Arial,sans-serif;color:#172033;padding:28px;font-size:13px}
  h1{font-size:20px;margin:0 0 4px} .muted{color:#667085;font-size:12px;margin-bottom:18px}
  table{width:100%;border-collapse:collapse;margin-top:12px}
  th,td{border-bottom:1px solid #e4e7ec;padding:8px 10px;text-align:left;font-size:12px}
  th{background:#fafbfc;color:#667085;font-size:11px}
  .foot{margin-top:24px;font-size:11px;color:#667085}
  @media print{body{padding:0}}
</style></head><body>
<h1>${esc(title)}</h1>
${bodyHtml}
<div class="foot">Generated by S4-BUSINESS-INVOICE TRACKER · ${new Date().toLocaleString()}</div>
</body></html>`;
}

function getPrintFrame(){
  let iframe = document.getElementById("s4PrintFrame");
  if(!iframe){
    iframe = document.createElement("iframe");
    iframe.id = "s4PrintFrame";
    iframe.title = "Print";
    iframe.setAttribute("aria-hidden", "true");
    iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;opacity:0;pointer-events:none";
    document.body.appendChild(iframe);
  }
  return iframe;
}

/**
 * Print when the platform supports it; on Android APK share a printable HTML file
 * (WebView has no working print dialog).
 * Returns Promise<boolean> — true if print dialog opened, false if file was shared/downloaded.
 */
export async function printHtmlDocument(title, bodyHtml){
  const html = buildDocHtml(title, bodyHtml);
  const safeName = (title || "document").replace(/\s+/g, "_") + ".html";

  if(isAndroidNative()){
    try{
      await deliverText(safeName, html, "text/html;charset=utf-8", title || "Print document");
      return false;
    }catch(err){
      console.warn("Android print-share failed", err);
      return false;
    }
  }

  try{
    const iframe = getPrintFrame();
    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if(!doc || !iframe.contentWindow){
      await deliverText(safeName, html, "text/html;charset=utf-8", title || "Document");
      return false;
    }
    doc.open();
    doc.write(html);
    doc.close();
    iframe.contentWindow.focus();
    iframe.contentWindow.print();
    return true;
  }catch(err){
    console.warn("Print failed, delivering file instead", err);
    await deliverText(safeName, html, "text/html;charset=utf-8", title || "Document");
    return false;
  }
}

export async function downloadHtmlDocument(filename, title, bodyHtml){
  const html = buildDocHtml(title, bodyHtml);
  const name = filename.endsWith(".html") ? filename : filename + ".html";
  await deliverText(name, html, "text/html;charset=utf-8", title || name);
}

function esc(s){
  return String(s||"").replace(/[&<>"']/g, m=>({ "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;" }[m]));
}

export function tableFromRows(headers, rows){
  const th = headers.map(h=> `<th>${esc(h)}</th>`).join("");
  const tr = rows.map(r=> `<tr>${r.map(c=> `<td>${esc(c)}</td>`).join("")}</tr>`).join("")
    || `<tr><td colspan="${headers.length}">No data</td></tr>`;
  return `<table><thead><tr>${th}</tr></thead><tbody>${tr}</tbody></table>`;
}

export { deliverBlob, deliverText, isAndroidNative };
