// Printable document → browser "Save as PDF" + HTML download for WhatsApp attach
// Uses a hidden iframe (not window.open) so popup blockers do not throw console errors.

function buildDocHtml(title, bodyHtml){
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  body{font-family:Segoe UI,Arial,sans-serif;color:#172033;padding:28px;font-size:13px}
  h1{font-size:20px;margin:0 0 4px} .muted{color:#667085;font-size:12px;margin-bottom:18px}
  table{width:100%;border-collapse:collapse;margin-top:12px}
  th,td{border-bottom:1px solid #e4e7ec;padding:8px 10px;text-align:left;font-size:12px}
  th{background:#fafbfc;color:#667085;font-size:11px}
  .foot{margin-top:24px;font-size:11px;color:#667085}
  @media print{body{padding:0}}
</style></head><body>
<h1>${esc(title)}</h1>
${bodyHtml}
<div class="foot">Generated by S4-BUSINESS-INVOICE TRACKER · ${new Date().toLocaleString()}</div>
</body></html>`;
}

function getPrintFrame(){
  let iframe = document.getElementById("s4PrintFrame");
  if(!iframe){
    iframe = document.createElement("iframe");
    iframe.id = "s4PrintFrame";
    iframe.title = "Print";
    iframe.setAttribute("aria-hidden", "true");
    iframe.style.cssText = "position:fixed;right:0;bottom:0;width:0;height:0;border:0;opacity:0;pointer-events:none";
    document.body.appendChild(iframe);
  }
  return iframe;
}

export function printHtmlDocument(title, bodyHtml){
  const html = buildDocHtml(title, bodyHtml);
  try{
    const iframe = getPrintFrame();
    const doc = iframe.contentDocument || iframe.contentWindow?.document;
    if(!doc || !iframe.contentWindow){
      downloadHtmlDocument((title || "document").replace(/\s+/g, "_") + ".html", title, bodyHtml);
      return false;
    }
    doc.open();
    doc.write(html);
    doc.close();
    // Print in the same click gesture (no setTimeout) so browsers allow the dialog
    iframe.contentWindow.focus();
    iframe.contentWindow.print();
    return true;
  }catch(err){
    console.warn("Print failed, downloading HTML instead", err);
    downloadHtmlDocument((title || "document").replace(/\s+/g, "_") + ".html", title, bodyHtml);
    return false;
  }
}

export function downloadHtmlDocument(filename, title, bodyHtml){
  const html = buildDocHtml(title, bodyHtml);
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" }));
  a.download = filename.endsWith(".html") ? filename : filename + ".html";
  a.click();
  setTimeout(()=> URL.revokeObjectURL(a.href), 5000);
}

function esc(s){
  return String(s||"").replace(/[&<>"']/g, m=>({ "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;" }[m]));
}

export function tableFromRows(headers, rows){
  const th = headers.map(h=> `<th>${esc(h)}</th>`).join("");
  const tr = rows.map(r=> `<tr>${r.map(c=> `<td>${esc(c)}</td>`).join("")}</tr>`).join("")
    || `<tr><td colspan="${headers.length}">No data</td></tr>`;
  return `<table><thead><tr>${th}</tr></thead><tbody>${tr}</tbody></table>`;
}
