// Printable document → browser "Save as PDF" + HTML download for WhatsApp attach

export function printHtmlDocument(title, bodyHtml){
  const w = window.open("", "_blank", "noopener,noreferrer,width=900,height=700");
  if(!w) throw new Error("Popup blocked — allow popups to export PDF");
  w.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  body{font-family:Segoe UI,Arial,sans-serif;color:#172033;padding:28px;font-size:13px}
  h1{font-size:20px;margin:0 0 4px} .muted{color:#667085;font-size:12px;margin-bottom:18px}
  table{width:100%;border-collapse:collapse;margin-top:12px}
  th,td{border-bottom:1px solid #e4e7ec;padding:8px 10px;text-align:left;font-size:12px}
  th{background:#fafbfc;color:#667085;font-size:11px}
  .foot{margin-top:24px;font-size:11px;color:#667085}
  @media print{body{padding:0}}
</style></head><body>
<h1>${esc(title)}</h1>
${bodyHtml}
<div class="foot">Generated by S4-BUSINESS-INVOICE TRACKER · ${new Date().toLocaleString()}</div>
<script>window.onload=function(){setTimeout(function(){window.print()},200)}</script>
</body></html>`);
  w.document.close();
}

export function downloadHtmlDocument(filename, title, bodyHtml){
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  body{font-family:Segoe UI,Arial,sans-serif;color:#172033;padding:28px;font-size:13px}
  h1{font-size:20px;margin:0 0 4px} table{width:100%;border-collapse:collapse;margin-top:12px}
  th,td{border-bottom:1px solid #e4e7ec;padding:8px 10px;text-align:left;font-size:12px}
  th{background:#fafbfc;color:#667085}
</style></head><body><h1>${esc(title)}</h1>${bodyHtml}</body></html>`;
  const a = document.createElement("a");
  a.href = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" }));
  a.download = filename.endsWith(".html") ? filename : filename + ".html";
  a.click();
  setTimeout(()=> URL.revokeObjectURL(a.href), 5000);
}

function esc(s){
  return String(s||"").replace(/[&<>"']/g, m=>({ "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;" }[m]));
}

export function tableFromRows(headers, rows){
  const th = headers.map(h=> `<th>${esc(h)}</th>`).join("");
  const tr = rows.map(r=> `<tr>${r.map(c=> `<td>${esc(c)}</td>`).join("")}</tr>`).join("")
    || `<tr><td colspan="${headers.length}">No data</td></tr>`;
  return `<table><thead><tr>${th}</tr></thead><tbody>${tr}</tbody></table>`;
}
